project_id = "arzthloosvnasokxygfo"

[functions.handle-purl]
verify_jwt = false

[functions.submit-lead-form]
verify_jwt = false

[functions.generate-template-design]
verify_jwt = true

[functions.regenerate-template-element]
verify_jwt = true

[functions.dr-phillip-chat]
verify_jwt = false
